# Leetcode Link -- https://leetcode.com/problems/find-the-difference/description/

# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        
        # Testing case 1: "a", "ab"
        # Testing case 2: "a", "aa"  -> Missing!!!
        # Testing case 3: "abc", "bdca"
        charMap = {}
        for sC in s:
            if sC in charMap:
                charMap[sC] += 1 
            else:
                charMap[sC] = 1
                
        for tC in t:
            if tC not in charMap:
                return tC
            else:
                charMap[tC] -= 1
                if charMap[tC] < 0:
                    return tC
s = Solution()

print s.findTheDifference("a", "aa")
print s.findTheDifference("a", "ab")
print s.findTheDifference("abc", "bcda")