# Leetcode Link -- https://leetcode.com/problems/find-the-difference/description/

# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        
        # Testing case 1: "a", "ab"
        # Testing case 2: "a", "aa"  -> Missing!!!
        # Testing case 3: "abc", "bdca"
        charSet = {}
        for c in s:
            if c in charSet:
                charSet[c] += 1 
            else:
                charSet[c] = 1
                
        for l in t:
            if l not in charSet:
                return l
            else:
                charSet[l] -= 1
                if charSet[l] < 0:
                    return l
s = Solution()

print s.findTheDifference("a", "aa")
print s.findTheDifference("a", "ab")
print s.findTheDifference("abc", "bcda")